// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1PWlr0iMcupuNWLXUSSC9dDECmJqab9E',
    appId: '1:1067358140411:web:65d3c3d98e10e778ef7d5e',
    messagingSenderId: '1067358140411',
    projectId: 'bubbl-24c2f',
    authDomain: 'bubbl-24c2f.firebaseapp.com',
    storageBucket: 'bubbl-24c2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4_IBirvVMeL3aKiaOs_ZJ7INyGrthpNU',
    appId: '1:1067358140411:android:ca8b65c616e78a21ef7d5e',
    messagingSenderId: '1067358140411',
    projectId: 'bubbl-24c2f',
    storageBucket: 'bubbl-24c2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdNExZWHhmHbYMLzjhTcmvcZjwZhThFZw',
    appId: '1:1067358140411:ios:a578d2c362cf9af2ef7d5e',
    messagingSenderId: '1067358140411',
    projectId: 'bubbl-24c2f',
    storageBucket: 'bubbl-24c2f.appspot.com',
    iosClientId: '1067358140411-9nii8bq73qaiiphucmr9s2pkm574qgn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubbl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdNExZWHhmHbYMLzjhTcmvcZjwZhThFZw',
    appId: '1:1067358140411:ios:a578d2c362cf9af2ef7d5e',
    messagingSenderId: '1067358140411',
    projectId: 'bubbl-24c2f',
    storageBucket: 'bubbl-24c2f.appspot.com',
    iosClientId: '1067358140411-9nii8bq73qaiiphucmr9s2pkm574qgn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubbl',
  );
}
